In [23]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as mp
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from xgboost import XGBRegressor
import pickle

In [24]:
dataset = pd.read_csv("/content/BostonHousing.csv")

In [25]:
dataset

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [26]:
dataset.isnull().sum()


crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
price      0
dtype: int64

In [27]:
x = dataset.drop('price',axis=1)
y = dataset['price']

In [28]:
x

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [29]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: price, Length: 506, dtype: float64

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=32)

In [31]:
print(x.shape, x_train.shape, x_test.shape)

(506, 13) (404, 13) (102, 13)


In [32]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [33]:
model_prediction = model.predict(x_train)
model_prediction

array([22.6199477 , 34.35750316, 12.93964048, 10.03258907, 19.77795589,
       36.14744068, 20.27704418, 27.40448574, 24.65418183, 20.85267695,
       13.7481405 , 17.20020514, 18.67188164, 13.08931566, 17.14242815,
       16.29236852, 39.24224595, 24.67107244, 28.9658271 , 13.09596298,
       15.34970905, 28.93534833, 32.6988109 , 25.4991045 , 15.15003439,
       24.68924804, 19.9450864 , 18.3116785 , 13.26000171, 28.89844275,
       11.24891549, 14.47767151,  9.51521182, 17.54660814, 28.8215794 ,
       19.03389785, 15.23265101, 32.0785574 , 18.83790304, 22.47383067,
       36.41840569,  6.5885944 , 16.53743833,  2.48232493, 20.04521531,
       18.27210729, 22.49561332,  7.28795821, 18.77043191, 21.0150735 ,
       20.29656895, 23.25871898, 22.6497348 , 21.31727202, 27.51304853,
       25.02254877, 33.89761391, 21.00501762, 18.36186452, 17.28460236,
       33.52181283, 22.30933658, 19.44877638, 23.51408943, 40.16936645,
       25.2304554 , 13.93819587, 30.50282913, 18.1118657 , 16.82

In [34]:
s1 = metrics.r2_score(model_prediction, y_train)
print("R2 Score:",s1)
s2 = metrics.mean_absolute_error(model_prediction, y_train)
print("Mean Absolute Error:",s2)

R2 Score: 0.6707268693410465
Mean Absolute Error: 3.1739117760491076


In [35]:
input = np.array([[0.06905,	0.0,	2.18,	0,	0.458,	7.147,	54.2,	6.0622,	3,	222,	18.7,	396.90,	5.33]])
model.predict(input)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([28.28291505])

In [36]:
model2 = XGBRegressor()
model2.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [37]:
model_prediction = model2.predict(x_train)
model_prediction

array([17.427113 , 35.20428  , 12.288673 , 13.20012  , 19.896008 ,
       49.987823 , 17.103125 , 22.014324 , 24.69435  , 20.374037 ,
       17.188927 , 14.100669 , 16.60914  , 13.800389 , 12.991604 ,
       15.605804 , 43.51693  , 24.292465 , 26.3898   , 12.71299  ,
       17.199091 , 24.093931 , 31.469545 , 21.603619 , 16.198479 ,
       20.725298 , 19.41243  , 19.594341 , 11.316068 , 22.504389 ,
        6.301422 , 13.497444 ,  8.714229 ,  7.210296 , 28.389505 ,
       12.501692 , 15.396395 , 31.088198 , 14.612138 , 19.307512 ,
       36.009827 , 10.202385 , 10.200082 , 17.897717 , 13.299233 ,
       14.511283 , 22.184803 , 10.392743 , 22.596247 , 21.695724 ,
       18.597403 , 24.710964 , 22.492945 , 17.01073  , 23.898653 ,
       23.100592 , 37.897724 , 19.988535 , 18.382933 , 17.201954 ,
       32.003387 , 11.913422 , 19.897299 , 19.400463 , 49.991573 ,
       21.606842 , 13.996721 , 24.801863 , 19.956585 , 19.06045  ,
       15.401435 , 19.805044 ,  5.5863614, 24.510479 , 20.0872

In [38]:
s1 = metrics.r2_score(model_prediction, y_train)
print("R2 Score:",s1)
s2 = metrics.mean_absolute_error(model_prediction, y_train)
print("Mean Absolute Error:",s2)

R2 Score: 0.9999982099984474
Mean Absolute Error: 0.008265750242932017


In [39]:
input = np.array([[0.06905,	0.0,	2.18,	0,	0.458,	7.147,	54.2,	6.0622,	3,	222,	18.7,	396.90,	5.33]])
model2.predict(input)

array([36.19784], dtype=float32)

In [40]:
pickle.dump(model,open("house_price_pred.pkl","wb"))